### ISSUE TITLE
react-redux integration errors with v3

### ISSUE THREAD

**Issue by rssfrncs** [dai-shi/proxy-memoize#104]
With v2.x versions of proxy-memoize everything runs as expected. Trying to upgrade to V3 and we encounter seemingly circular dep issues with certain reducers (redux) being undefined `No reducer provided for key "session"`. It only seems to be reducer files that import proxy-memoize (v3) for selector functions. As soon as i downgrade to v2.x the errors go away.

Any thoughts? I apologise this is a bit abstract.

**Comment by rssfrncs** [comment]
Oddly enough upgrading to v3 (broken), downgrade to v2 (working), upgrade to v3 (working). I wonder if something odd is happening with nextjs (v12) and the change to modules in v3.

**Comment by dai-shi** [comment]
If there's a difference between v2.0.6 and v3.0.0, #99 is the change.
I wonder if the newer nextjs v13&v14 makes any changes.
If it works with the newer version, I think we'd leave it and you can keep using v2 meanwhile.

**Comment by rssfrncs** [comment]
Yeah that was my thought. It's quite a lift for us to get off of next 11 but we are hoping to do it. I wonder if i can alias the imports (webpack next config) to resolve the cjs files instead...

**Comment by rssfrncs** [comment]
yes you can use resolve.alias e.g.

```
 alias: {
          ...config.resolve.alias,
          'proxy-memoize': path.resolve(
            './node_modules/proxy-memoize/dist/cjs/index.js',
          ),
          'proxy-compare': path.resolve(
            './node_modules/proxy-compare/dist/cjs/index.js',
          ),
        },
```

Next is now happy and i do not get the weird reducer not defined errors anymore. Is there a reason to not import the cjs files into browser code? Any node specific code? Thanks.

**Comment by dai-shi** [comment]
tbh, I don't know why v3 doesn't work well. It's the configuration that I use for most of my libs.

**Comment by rssfrncs** [comment]
Yeah we have the same problem with the latest Immer which looks like it is now using a similar configuration. 

Do you think it's okay to rely on aliasing to CJS for the time being until we upgrade / move away from Next?

**Comment by dai-shi** [comment]
Yes, as for proxy-memoize, CJS and EMS are for the same transpilation target, and only the difference is the file format. So, no issues with using CJS.
