### ISSUE TITLE
Sourcemaps not set up correctly?

### ISSUE THREAD

**Issue by markerikson** [dai-shi/proxy-memoize#11]
I'm trying to debug #10 , but I don't see any indication of the `proxy-memoize` source showing up in the Chrome DevTools.  I can't find any filenames with `proxy-memoize` in the path, and if I try to put a breakpoint right before the `memoize()` call and step into it, the DevTools debugger steps into random lines of the RTK source before ending up back in the app code.

This is using https://github.com/reduxjs/redux-fundamentals-example-app/commit/f270ea1c91362c74e1ca88a4982d8545b4984b11 , which is built with `react-scripts@3.4.3`.

Just wondering if somehow the sourcemaps aren't built/defined correctly.

On the other hand, loading https://codesandbox.io/s/proxy-memoize-demo-c1021 into Chrome, I see the `proxy-memoize` files under `node_modules` just fine.  So, this could also be a build environment issue somehow.

**Comment by markerikson** [comment]
I'm wondering if this is a clash between RTK's sourcemaps and PM's sourcemaps somehow.  Both point to a `'../src/index.ts'` file as one of their sources, and trying to step into `memoize()` is specifically showing RTK's `src/index.ts` instead.

**Comment by dai-shi** [comment]
It's using microbundle to build. I'm not sure what to do...

**Comment by markerikson** [comment]
Yeah, I saw that.  

I can't figure out if this is an RTK thing, PM thing, CRA thing, or something else.

**Comment by dai-shi** [comment]
If this issue isn't super critical, I will consider to make this library v1.0.0.

**Comment by dai-shi** [comment]
Closing as nothing actionable. Can reopen if someone has a suggestion.
