### ISSUE TITLE
The last example says it can't be written in Reselect, but it can. 

### ISSUE THREAD

**Issue by todorpr** [dai-shi/proxy-memoize#15]
I just discovered `proxy-memoize` recently I think it has a good potential.

One thing I think is incorrect is the statement that the last example can't be written in `reselect` 

The last example is this one:
```js
const todoTextsSelector = memoize(state => state.todos.map(todo => todo.text));
```

Here is how I see it in `reselect`:
```js
const state = {
  todos: [{ text: 'aaa' }, { text: 'bbb' }]
}

const todoTextSelector = createSelector(
  state => state.todos,
  todos => todos.map(todo => todo.text)
)

console.log(todoTextSelector(state)) // ["aaa", "bbb"]
console.log(todoTextSelector(state)) // ["aaa", "bbb"]
console.log(todoTextSelector(state)) // ["aaa", "bbb"]
console.log(todoTextSelector(state)) // ["aaa", "bbb"]
console.log(todoTextSelector.recomputations()) // 1

```

**Comment by dai-shi** [comment]
Thanks for jumping in.

My apologies, that was too easy without detailed info.

```js
const state = {
  todos: [{ text: 'aaa', completed: true }, { text: 'bbb', completed: false }]
}
```
We assume this case, and when only `completed` is changed.

Please refer this too: https://github.com/reduxjs/react-redux/issues/1653#issuecomment-727515572

**Comment by todorpr** [comment]
Aha, now I get it. You are absolutely right - `reselect`'s selector will recompute in this case, whereas `memoize`'s won't.
