### ISSUE TITLE
TypeError: Object is not a function

### ISSUE THREAD

**Issue by rpavlovs** [dai-shi/proxy-memoize#22]
When running example code in my RN app I get:

```ts
import memoize from 'proxy-memoize'
const fn = memoize(obj => ({ sum: obj.a + obj.b, diff: obj.a - obj.b }))
```
=>

![image](https://user-images.githubusercontent.com/634881/123486999-f58d1380-d5c1-11eb-92d8-ed0ee223074e.png)

For some reason that import notation results in `.deafult` being still present:
![image](https://user-images.githubusercontent.com/634881/123487104-2b31fc80-d5c2-11eb-8538-14f278ece60e.png)

If I do `memoize.deafult(...)` TS complains, but it works.

Am I importing it wrong? Or could it be something React Native specific? Hermes?

**Comment by dai-shi** [comment]
Hmmm, so RN picks UMD build but not with compatibility?

Does this work? `import memoize from 'proxy-memoize/dist/index.modern';`
Well, TS may complain anyway.

---
RN is such a common target, so I wish to fix.
https://facebook.github.io/metro/docs/configuration/#resolvermainfields
Adding `"module"` may fix, but doesn't seem ideal.
I wonder how common RN libs bundle CJS builds...

**Comment by nibmz7** [comment]
`import memoize from 'proxy-memoize/dist/index.modern';` worked for me.

And to fix the typing. A temp solution 😅

```
index.d.ts

declare module 'proxy-memoize/dist/index.modern' {
  declare const memoize: <Obj extends object, Result>(
    fn: (obj: Obj) => Result,
    options?:
      | {
          size?: number | undefined;
        }
      | undefined
  ) => (obj: Obj) => Result;

  export default memoize;
}
```

**Comment by dai-shi** [comment]
Hi folks,
A proper fix came to my mind. #25 
Please see https://ci.codesandbox.io/status/dai-shi/proxy-memoize/pr/25
and find "Local install instructions".
Let me know if it fixes the issue.

**Comment by dai-shi** [comment]
Hmm, I may need to fix the upstream library too.

**Comment by nibmz7** [comment]
Tried and works 🙌

**Comment by dai-shi** [comment]
Thanks. Good to know. (I don't know why the upstream library doesn't complain.)

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/proxy-memoize/v/0.3.5

**Comment by groyee** [comment]
I am getting this error on version 1.2... any workaround?

**Comment by dai-shi** [comment]
Is it with jest? If so, #30 and #42. Otherwise, please open a new issue with a reproduction.
