### ISSUE TITLE
TypeError "_proxyMemoize.default is not a function" in Jest test

### ISSUE THREAD

**Issue by nilshartmann** [dai-shi/proxy-memoize#30]
When testing our TypeScript-based React application using Jest test, we receive the following error:

```
TypeError: (0 , _proxyMemoize.default) is not a function
```

I've tested 0.3.4 and 0.3.6 of proxy-memoize and in both versions this error occurs. Building and running our application works fine (using Webpack default configuration from create-react-app), and we're very happy with it! It's only a problem when running our jest tests.

A reproducible project can be found here: https://github.com/nilshartmann/proxy-memo-playground. You can find a simple test case in `src/App.test.tsx`. When you run the test using `yarn test` the error occurs (all other source files are not relevant for the problem)

I think this is somehow related to the different module systems, maybe something similar as #22 ?

**Comment by dai-shi** [comment]
Yes, it's related to module system issue I've been struggling with. We are in the transition from babel modules to real ES modules. I wish we could fix this, or at least the major use case.

Here's the workaround I came up with for this specific issue:
```diff
diff --git a/package.json b/package.json
index 0d794ae..ec04901 100644
--- a/package.json
+++ b/package.json
@@ -29,6 +29,12 @@
       "react-app/jest"
     ]
   },
+  "jest": {
+    "moduleNameMapper": {
+      "^proxy-memoize$": "<rootDir>/node_modules/proxy-memoize/dist/index.modern.js"
+    },
+    "transformIgnorePatterns": ["/node_modules/(?!proxy-memoize)"]
+  },
   "browserslist": {
     "production": [
       ">0.2%",
```


jest 27 might also fix it: https://jestjs.io/ja/docs/ecmascript-modules

**Comment by nilshartmann** [comment]
Thanks a lot for your hint, works for me!
