### ISSUE TITLE
uncorrected export

### ISSUE THREAD

**Issue by geekplux** [dai-shi/proxy-memoize#31]
An error "TypeError: proxy_memoize__WEBPACK_IMPORTED_MODULE_6___default(...) is not a function" would pop out when I use this lib in a next.js project.

I also tied the solution like #22 

```js
import memoize from 'proxy-memoize/dist/index.modern';
```

but got "Module not found: Package path ./dist/index.modern is not exported from package"

**Comment by geekplux** [comment]
Quick response! thanks.

It's easy to create a reproduction, just creating a next.js project according to its doc:
```sh
yarn create next-app
```
then import proxy-memoize in the `page/index.js` using default importing or the method I mentioned, and you will get the same error when calling the memoize function.

**Comment by dai-shi** [comment]
Thanks for the reproduction step.
#32 should fix it.
https://ci.codesandbox.io/status/dai-shi/proxy-memoize/pr/32
You can try Local Install Instructions in ☝️ .
