### ISSUE TITLE
Performance hit when upgrading from 1.0.0 to 1.1.0 

### ISSUE THREAD

**Issue by dutziworks** [dai-shi/proxy-memoize#49]
Hey @dai-shi, we recently upgraded a pretty big code base from proxy-memoize 1.0.0 to 1.1.0 and found that performance-wise that app took a big hit.

I'll try seeing if I can setup a demo for this, since I can't share the code unfortunately.

**Update:**

Here is a screenshot of the Performance panel (for version 1.1.0), it's showing a keydown handler that takes 320ms:

![CleanShot 2022-07-09 at 20 52 01@2x](https://user-images.githubusercontent.com/81780859/178117866-7a42cc81-77e5-408c-b858-b119ae259c4c.png)

That same keydown handler when running on 1.0.0 (that's the only change I made, `yarn add proxy-memoize@1.0.0`) takes 17.58ms:

![CleanShot 2022-07-09 at 21 23 16@2x](https://user-images.githubusercontent.com/81780859/178118337-b1a1576e-3b8e-40f8-8a85-02227dd77233.png)

**Comment by dutziworks** [comment]
Sorry for this crude issue submission, I will also try setting up a simple performance measurement!

**Comment by dutziworks** [comment]
Also, in the first screenshot, there's a function named `k`, which is defined in `index.ts` (the red arrow points there).

When clicking on the `index.ts` link, I'm taken to this file:

![CleanShot 2022-07-09 at 20 53 54@2x](https://user-images.githubusercontent.com/81780859/178118664-ca3599dd-ca8f-436e-91a5-ba35e4de9622.png)

**Comment by dai-shi** [comment]
Thanks for reporting! It's unexpected, and we should figure it out.

https://github.com/dai-shi/proxy-memoize/blob/main/CHANGELOG.md#110---2022-06-14

We have three changes in the version.
Can you investigate which causes the issue? you can visit the PRs and find codesandbox builds there.

**Comment by dutziworks** [comment]
Sure!

8dd02c012e157f5cf9da19451cf2206401b9f4a4 - this commit is the one that introduces the performance hit.

That's also the reason we've upgraded, to fix #44.

I noticed that if I don't render one of our more selector-intensive components (that _is_ using nested selectors) we don't suffer that perf hit.

I'll look more into that.

**Comment by dutziworks** [comment]
I've pinpointed it down to a single, pretty simple component.

Simplifying it a bit more, you end up with this:

```ts
import React from 'react';
import { useSelectActorsByCharacters } from '../../pages/Composer/Composer.selectors';
import { Character } from '../../types/character';

export default function TracksPanelCharacterNode({ character }: { character: Character }) {
  const actor = useSelectActorsByCharacters()[character.id];

  return <div>{actor?.name}</div>;
}
```

When this renders ~60 times, things get slow.

The code for the selector:

```ts
/**
 * Returns all the characters (and their localized episode casts entry) for
 * the current localized episode that appear in the cast table (or, "casted"
 * characters).
 */
export const selectActorsByCharacters = createAppSelector((state) => {
  const { data: speakers } = api.endpoints.listSpeakers.select({ filter: { archived: { ne: true } } })(state);

  const map: { [characterId: string]: Speaker } = {};
  state.composer.characters?.forEach((character) => {
    const actor = speakers?.find((speaker) => speaker.id === character.actorId);

    if (actor) {
      map[character.id] = actor;
    }
  });

  return map;
});

export function useSelectActorsByCharacters() {
  return useAppSelector(useCallback(selectActorsByCharacters, []));
}
```

- `api.endpoints` is RTK Query.
- `api.endpoints.listSpeakers.select({ filter: { archived: { ne: true } } })(state)` returns a pretty big array (~2000 items) using RTK's `selector` util.
- `state.composer.characters` is a pretty slim array (<40 items).

I'll see if I can reproduce this on CodeSandbox.

**Comment by dai-shi** [comment]
Oh, I see. #46 made `touchAffected` called every time, which drops performance. Thanks for investigating!!!

Yeah, a minimal reproduction in codesandbox would help. It would even be nice to drill- down an undesired behavior and create a test. And, then we can try fixing/optimizing it. (At this point, I'm not sure how feasible it is.)

**Comment by dutzi** [comment]
Cool! 

I did try but didn't manage to reproduce this in a simpler setup, yet. I'll give it another go later today!

**Comment by Bardiamist** [comment]
Also faced with performance problem on big code base
Revert from 1.2.0 to 1.0.0 defenetely helped

**Comment by dai-shi** [comment]
Can any of you help investigating the issue?

I assume L91 is slow.
https://github.com/dai-shi/proxy-memoize/blob/05c5b873c65d079d953ef9f08833702e29fd2978/src/index.ts#L91

Can you comment it out and see if it improves? (surely, it breaks some cases, but not everything.)

**Comment by Bardiamist** [comment]
I commented line 91

Also I changed in `package.json`:
```
"react-native": "./src/index.ts",
```

Not helped

**Comment by dai-shi** [comment]
Oh, really? I need your further help then.
https://github.com/dai-shi/proxy-memoize/blob/main/CHANGELOG.md#110---2022-06-14
We have three PRs from v1.0.0 to v1.1.0. Can you narrow it down?

**Comment by Bardiamist** [comment]
Problem appeared here: https://github.com/dai-shi/proxy-memoize/commit/8dd02c012e157f5cf9da19451cf2206401b9f4a4

**Comment by dai-shi** [comment]
Hmm, can you comment out other `touchAffected` statements in `memoize` function? Hope one of which causes the issue.

**Comment by Bardiamist** [comment]
Helped if comment only line 76

**Comment by dai-shi** [comment]
Thanks. Good to know. But, at the same time, I don't think we have an ideal fix for all use cases. Maybe an option to skip `touchAffected` at L76, which even breaks the behavior?

**Comment by Bardiamist** [comment]
¯\_(ツ)_/¯

**Comment by Bardiamist** [comment]
I tried
```
"proxy-memoize": "git+ssh://git@github.com/dai-shi/proxy-memoize.git#fix/issue-49",
```

And did this
```
const resultCache = null;
```

Bad performance

**Comment by dai-shi** [comment]
Can you try `noWeakMap: true`?

**Comment by dai-shi** [comment]
Oh, please use codesandbox build.

**Comment by Bardiamist** [comment]
> Can you try `noWeakMap: true`?

There will be no difference with `const resultCache = null;`

> Oh, please use codesandbox build.

Idk how and will be no difference

**Comment by dai-shi** [comment]
Oh, so do you mean you edit the source code and compile on your end? Not sure why it doesn't change.

**Comment by Bardiamist** [comment]
I edit source code and use it as described [here](https://github.com/dai-shi/proxy-memoize/issues/49#issuecomment-1321386484)

> Not sure why it doesn't change.

Because `noWeakMap` leads only to `const resultCache = null;`

**Comment by dai-shi** [comment]
It then skip L76 touchAffected, right? Hmm.

**Comment by Bardiamist** [comment]
> It then skips L76 touchAffected, right? Hmm.

Right
Bad performance should be because no cache at all

**Comment by dai-shi** [comment]
Okay, so tier-1 cache helps in your case. Thought it gets new objects. 
How about having bigger `size` option?


Can you create a small contrived example to reproduce the issue?

**Comment by dai-shi** [comment]
> > Oh, please use codesandbox build.
> 
> Idk how and will be no difference

It was this:
https://ci.codesandbox.io/status/dai-shi/proxy-memoize/pr/53
"Local Install Instructions"

> i need just one memoized value

Hmm, but then in that case, `resultCache` shouldn't be useful.

I also wonder if the OP case is the same.

I don't feel like I'm able to create an example to reproduce this very easily. Would be nice if we could create a test case though.

**Comment by dai-shi** [comment]
@dutziworks @dutzi Are you still around?

**Comment by dai-shi** [comment]
To move things forward, I blindly _assume_ #53 fixes this issue.

@dutziworks Let me know, if it doesn't the case, and I will reopen this issue. (Or, maybe we should open a new one as this issue is a bit stale.)

@Bardiamist Your case seems different from this issue. Please try to create a small reproduction and open a new issue.

**Comment by Bardiamist** [comment]
I use version 1.0.0
Maybe more right solution to revert changes which led to the slowdown

**Comment by dai-shi** [comment]
The change was made to fix a bug behavior. Maybe, it was fast because it skipped some calculations. I wish to make it fast, but so far, I don't even know which part is causing slowdown. Please make a small reproduction, please.

**Comment by Bardiamist** [comment]
Hey @dai-shi I reproduced problem

Here is small example:
```
const memoize = require('proxy-memoize');

const selectorsCount = 100;

const reduxState = {
  books: [],
};

for (let index = 0; index < 1000; index += 1) {
  reduxState.books.push({
    isActive: true,
  });
}


const selectActiveBookByName = memoize(({
  books,
}) => books.filter((book) => book.active));

for (let index = 0; index < selectorsCount; index += 1) {
  selectActiveBookByName(reduxState);
}

const nextReduxState = { ...reduxState, b: '' };

for (let index = 0; index < selectorsCount; index += 1) {
  const startTime = performance.now();
  selectActiveBookByName(nextReduxState);
  console.log(performance.now() - startTime);
}

```

Selectors from this example on my machine takes:
v1.0.0: 0.0005 ms
v1.1.0: 0.09 ms
v2.0.0: 0.1 ms

Please reopen this issue and try to fix/optimize

**Comment by dai-shi** [comment]
Thanks for the reproduction! Can you please open a new issue. It might be the same cause, but let's start with fresh place.

**Comment by Bardiamist** [comment]
@dai-shi  I'd prefer to keep history but ok, created [new issue](https://github.com/dai-shi/proxy-memoize/issues/59)
