### ISSUE TITLE
Jest is not a function error

### ISSUE THREAD

**Issue by scaki** [dai-shi/proxy-memoize#54]
In our Next js project, we use your package so that the selectors respond when there is a change. But our tests give the following error. How can we solve this?

`TypeError: (0 , _proxyMemoize.default) is not a function`

**Packages details:**
"next": "^13.0.2"
"redux": "^4.2.0"
"react-redux": "^8.0.2"
"next-redux-wrapper": "^8.0.0"
"reselect": "^4.1.6"
"proxy-memoize": "^1.2.0"

**Comment by dai-shi** [comment]
Seems #42 is related.

**Comment by scaki** [comment]
I don't understand how to fix the problem

**Comment by dai-shi** [comment]
It's not solved, unfortunately. A workaround is to add `"^proxy-memoize$": "<rootDir>/node_modules/proxy-memoize/dist/wrapper.cjs"` in jest moduleNameWrapper.

Please continue discussion in #42.
