### ISSUE TITLE
Performance drop after update from 1.0.0 to 1.1.0

### ISSUE THREAD

**Issue by Bardiamist** [dai-shi/proxy-memoize#59]
Here is small example:
```
const memoize = require('proxy-memoize');

const reduxState = {
  books: [],
};

for (let index = 0; index < 1000; index += 1) {
  reduxState.books.push({
    isActive: true,
  });
}

const selectActiveBooks = memoize(({
  books,
}) => books.filter((book) => book.active));

selectActiveBooks(reduxState);

const nextReduxState = { ...reduxState, b: '' };

for (let index = 0; index < 100; index += 1) {
  const startTime = performance.now();
  selectActiveBooks(nextReduxState);
  console.log(performance.now() - startTime);
}
```

Selectors from this example on my machine takes:
v1.0.0: 0.0005 ms
v1.1.0: 0.09 ms
v2.0.0: 0.1 ms

[Previous issue](https://github.com/dai-shi/proxy-memoize/issues/49)

Please try to fix/optimize it

**Comment by dai-shi** [comment]
Thanks for the benchmarking example. That's very helpful.
#60 should fix it.
https://ci.codesandbox.io/status/dai-shi/proxy-memoize/pr/60
See "Local Install Instructions" ☝️

**Comment by Bardiamist** [comment]
Nice! Looks good
