### ISSUE TITLE
What is the difference with memoize-state?

### ISSUE THREAD

**Issue by valerii15298** [dai-shi/proxy-memoize#65]
What is the difference with `memoize-state`?

**Comment by dai-shi** [comment]
Thanks for asking! What kind of answer are you expecting?

**Comment by valerii15298** [comment]
`memoize-state` just seems very similar. So I was just curious what is the difference. I see your library has more docs and examples, which means easier to use.

**Comment by dai-shi** [comment]
Their goals are the same.
`memoize-state` is based on `proxyequal`.
`proxy-memoize` is based on `proxy-compare`.

I implemented `proxy-compare`, after learning @theKashey's `proxyequal` as a prior art, with lots of his help.
There are some differences like `proxy-compare` doesn't support `Map` intentionally. In short, `proxy-compare` and `proxy-memoize` are more modern.

**Comment by valerii15298** [comment]
Thanks for explanation.
I think this can be closed now😆🙂
