### ISSUE TITLE
memoized function with large state takes a very long time.

### ISSUE THREAD

**Issue by gnawjaren** [dai-shi/proxy-memoize#68]
I have a very large state - and a selector which calculates values on this state. (touching many properties)
I tried to memoize this selector with proxy-memoize, but it takes a very long time. (~1000ms, vs ~1ms without memoize/with reselect)
Is this expected ? (high count of properties to compare ?)

Is there anything I can do about it ?

Here is a sandbox with a very simplified example. 
I included plain (no memoization), proxy-memoize, and reselect versions.

https://codesandbox.io/s/intelligent-pine-8i9lom?file=/src/index.test.js

This is the timing for the various versions:
<img width="513" alt="tests" src="https://user-images.githubusercontent.com/16381548/234919724-1d97baad-5874-4d2e-ad8e-78cc46c2fc25.png">

This is output of the Chrome Profiler:
<img width="522" alt="profile" src="https://user-images.githubusercontent.com/16381548/234912706-b6246ab2-78b3-4a01-a78a-c354e3893ad9.png">

Thank you very much for this project, I like this approach.

**Comment by dai-shi** [comment]
Hi, thanks for reporting.
We had some issues about performance drop before, but this looks like a new case.

We need to dig into it. Not sure if there's an easy way to fix.
Is anyone interested? Maybe @Aslemammad ?

**Comment by Aslemammad** [comment]
Can I be assigned to this one?

**Comment by dai-shi** [comment]
@gnawjaren Would you like to try #72?
https://ci.codesandbox.io/status/dai-shi/proxy-memoize/pr/72
☝️ Find "Local Install Instructions"

**Comment by gnawjaren** [comment]
I can confirm, it's blazing fast now. Thanks a lot.

**Comment by Aslemammad** [comment]
I'm happy we could acheive such results, Thank you for letting us know.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/proxy-memoize/v/2.0.4
