### ISSUE TITLE
Incorrect memoization when reading an unchanged property of a changed object

### ISSUE THREAD

**Issue by jeremy-deutsch** [dai-shi/proxy-memoize#7]
Codesandbox reproduction: https://codesandbox.io/s/keen-tree-r7pp2

I know this is probably a general issue with the model and so not something that can be fixed, but I think it's important to note anyway. Here's the example from my codesandbox:

```
const initialState = { pet: { type: "cat", weight: 20 } };
const changedState = { pet: { type: "cat", weight: 40 } };

const getCat = memoize((state) => {
  if (state.pet.type === "cat") {
    return state.pet;
  } else {
    return null;
  }
});

console.log(getCat(initialState)) // { type: "cat", weight: 20 }
console.log(getCat(changedState)) // { type: "cat", weight: 20 }, should be { type: "cat", weight: 40 } instead
```

In this example, `proxy-memoize` "sees" the `state.pet.type` access, and so decides to just return the previous result if `state.pet.type` is equal to the last `state.pet.type`, even though the new and previous result should have different `weight` values. Again, I don't know if there's a good solution for this, but I think it's worth it to note the issue.

**Comment by dai-shi** [comment]
Ah, nice catch! I think... I can fix this.
