### ISSUE TITLE
memoizeWithArgs returning wrongly cached result

### ISSUE THREAD

**Issue by IPWright83** [dai-shi/proxy-memoize#76]
I'm trying to use `memoizeWithArgs` and I'm finding that it's returning the wrong results - essentially returning results for a different set of args.

I'm calling it like so:
```
getScale: memoizeWithArgs((state: IState, field: string, type: "plot" | "brush") => {
  ... // returns a new function
}, { size: 50 });
```

It works to start with, returning correct values (see the `[70, 760]` in the watch window).
![image](https://github.com/dai-shi/proxy-memoize/assets/1374775/0198d8d3-0dfb-4139-b631-8eb313bd4c77)

Once a call with a different type (brush) is used, I correctly get different results:
![image](https://github.com/dai-shi/proxy-memoize/assets/1374775/b7443e67-3523-44ba-8ff7-f44a4fc814d3)

However each call there-after that has the same args as the first call (using `"plot"`, now starts returning the cached result from the call using `"brush"`).

![image](https://github.com/dai-shi/proxy-memoize/assets/1374775/5635595f-7aba-420b-b239-60f40ec71e6a)

I'm trying to debug it, but not having a huge amount of joy so far.

To reproduce the easiest way is to currently:
- Clone https://github.com/IPWright83/chart-it/tree/brushing
- Run a `pnpm install` from the root (you'll need `pnpm` installed to your system first)
- Run a `pnpm build`
- Run `cd packages/react`
- Run `pnpm storybook`
- Load `http://localhost:6006/?path=/story/xycharts-line--line-with-brush` in a browser
- Open up `SVGLine` in the browser source and add a breakpoint at the console log (line 24). 

At this point you should be able to see the incorrect calls. You can verify it's being memoised (and not the selector logic) by placing breakpoints in `chartSelectors` lines 182 and 198.

**Comment by dai-shi** [comment]
Thanks for reporting.
I don't think many people use `memoizeWithArgs` compared to `memoize`, so it can be a bug. If it's a bug, it should probably be reproducible with a few lines of code.
Can anyone help reproducing it minimally from the provided repo?

**Comment by IPWright83** [comment]
@dai-shi I'll give it a quick try and see if I can make any progress. Would you recommend using `memoize` and using an object instead then?

```
getScale: memoize(({ state: IState, field: string, type: "plot" | "brush" }) => {
```

**Comment by dai-shi** [comment]
If you look at the code, it's basically the same.

https://github.com/dai-shi/proxy-memoize/blob/9c157d73b2cf7cc6c3df745a43e1b7443b74022b/src/memoizeWithArgs.ts#L19-L28

**Comment by IPWright83** [comment]
Not having much joy with a simple replication https://codesandbox.io/s/nifty-sea-pcycvm?file=/src/proxy-memoize.test.ts this seems to be working fine. Any more thoughts on how I might debug this further?

**Comment by IPWright83** [comment]
Nevermind I think I'm being daft. I just realised that the function I'm using underneath is stateful 🤦🏻‍♂️
