### ISSUE TITLE
No change detection when length is accessed with same-length array 

### ISSUE THREAD

**Issue by Izhaki** [dai-shi/proxy-memoize#78]
When the length of an array is accessed within the function, an array with the same length will be seen as equal.

[CodeSandbox](https://codesandbox.io/s/proxy-memoize-length-issue-kr4545?file=/index.ts).

```ts
import { memoize } from "proxy-memoize";
import { produce } from "immer";

interface State {
  names: string[];
}

const logUpdated = memoize((state: State) => {
  const names = state.names;

  // Comment this line to see it works as expected
  // Or wrap with getUntracked(names)
  names.length;

  console.log("Updated!", names);
});

let state: State = {
  names: ["Smith"]
};

logUpdated(state); // => Updated! ["Smith"]

state = produce(state, (draft) => {
  draft.names = ["John"];
});

logUpdated(state); // => Nothing.

```

**Comment by dai-shi** [comment]
Yes, it's really how it's designed.
Accessing only `.length` means you only care about the length. So, unless the length changes, it won't re-evaluate.

What's tricky is if nothing is accessed, it assumes you care about the entire object (or array), so it re-evaluates.

**Comment by Izhaki** [comment]
Ah. Silly me! That makes perfect sense.

I ended up with this code after trying to troubleshoot other issues - In the actual code I've commented the lines accessing other things, but haven't commented them in my mind.

Thanks (and sorry for wasting your time).
